site_name: Портфолио технического писателя
nav:
  - Главная: index.md
  - Резюме: CV_Kasatkina.md
  - Пользовательская инструкция: user_guide.md
  - Инструкция для техподдержки: support_guide.md
  - API-документация: API-doc.md
theme: lantana
plugins:
  - ezlinks:
      wikilinks: true
